### ISSUE TITLE
css/fonts - add font-display

### ISSUE THREAD

**Issue by fvsch** [kaliop/frontend-style-guide#1]
Since `font-display` is getting support in more browsers (Firefox, Safari), time to add it as a recommendation in the performance section and in the example (e.g. for the heavy font).

Not sure which values to recommend. `fallback`, `swap`, `optional`?

https://kaliop.github.io/frontend-style-guide/2.0/css/#fonts
https://caniuse.com/#search=font-display
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

**Comment by ryuran** [comment]
`optional` si recommanded.

**Comment by fvsch** [comment]
Updated: https://kaliop.github.io/frontend-style-guide/2.0/css/#fonts

I mentioned `font-display` and linked to MDN. In the example code I used `fallback` rather than `optional`, it looks like a more general-purpose perceived perf improvement.
